#!/bin/bash

# SSL Pinning Bypass Test Script
# Usage: ./test_ssl_pinning.sh <package_name> <api_key>

set -e

PACKAGE=$1
API_KEY=$2

if [ -z "$PACKAGE" ] || [ -z "$API_KEY" ]; then
    echo "Usage: ./test_ssl_pinning.sh <package_name> <api_key>"
    exit 1
fi

echo "╔════════════════════════════════════════╗"
echo "║   SSL Pinning Bypass Test Suite       ║"
echo "╚════════════════════════════════════════╝"
echo ""

# Step 1: Collect context and detect frameworks
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Detecting SSL/Network frameworks"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
./gradlew run --quiet --args="-p $PACKAGE -c BASIC -o ssl_context.json"

# Check for OkHttp
if grep -q "OkHttp" ssl_context.json; then
    echo "✅ OkHttp detected - SSL pinning likely present"
    HAS_OKHTTP=true
else
    echo "⚠️  OkHttp NOT detected"
    HAS_OKHTTP=false
fi

# Check for SSL-related classes
echo ""
echo "🔍 Searching for SSL-related classes..."
grep -i "ssl\|certificate\|trust\|pin" ssl_context.json | grep "name" | head -5 || echo "  No obvious SSL classes found"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Testing Generic SSL Bypass"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

./gradlew run --quiet --args="-p $PACKAGE \
    -k $API_KEY \
    -q 'bypass ssl pinning' \
    --dry-run \
    -s generic_ssl_bypass.js"

echo "✅ Generic bypass script saved to: generic_ssl_bypass.js"
echo ""

# If OkHttp detected, try specific bypass
if [ "$HAS_OKHTTP" = true ]; then
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "STEP 3: Testing OkHttp-Specific Bypass"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    ./gradlew run --quiet --args="-p $PACKAGE \
        -k $API_KEY \
        -q 'hook okhttp3.CertificatePinner.check return null' \
        --dry-run \
        -s okhttp_ssl_bypass.js"

    echo "✅ OkHttp bypass script saved to: okhttp_ssl_bypass.js"
    echo ""
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Testing Multi-Hook SSL Bypass"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

./gradlew run --quiet --args="-p $PACKAGE \
    -k $API_KEY \
    -q 'hook okhttp3.CertificatePinner.check return null AND hook javax.net.ssl.X509TrustManager.checkServerTrusted return null' \
    --dry-run \
    -s multi_ssl_bypass.js"

echo "✅ Multi-hook bypass script saved to: multi_ssl_bypass.js"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Test Complete!"
echo ""
echo "Generated scripts:"
echo "  1. generic_ssl_bypass.js    - Generic LLM-generated bypass"
echo "  2. okhttp_ssl_bypass.js     - OkHttp-specific bypass"
echo "  3. multi_ssl_bypass.js      - Multi-hook comprehensive bypass"
echo ""
echo "Next steps:"
echo "  1. Review generated scripts"
echo "  2. Test manually:"
echo "     frida -U -f $PACKAGE -l generic_ssl_bypass.js --no-pause"
echo "  3. If fails, try okhttp_ssl_bypass.js"
echo "  4. Use multi_ssl_bypass.js for comprehensive bypass"
echo ""
echo "To test with actual execution (no dry-run):"
echo "  ./gradlew run --args=\"-p $PACKAGE -k $API_KEY -q 'bypass ssl pinning'\""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"